Real page
Hamas2000/-Technical-Documentation-Page pull request #1
Opened 2024-05-28 10:43 UTC by Hamas2000

this is a website that has information about js docmentation.

2024-05-28 11:29 UTC, ahzamir requested changes
### Hi @Hamas2000  🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements

- You have done a great job implementing all the requirements and your code passes all checks on the freecodecamp website.
- Your project has a README.md file but your file does not contain the information about your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
![image](https://github.com/Hamas2000/-Technical-Documentation-Page/assets/96838030/054d21b0-4c86-4e4d-a18e-825e8c3e709d)
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-30 10:09 UTC, Hamas2000 commented
@ahzamir Thank you for your review. I added a readme file.

2024-06-01 07:14 UTC, ahzamir approved these changes
### Hi @Hamas2000 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/Hamas2000/-Technical-Documentation-Page/assets/96838030/054d21b0-4c86-4e4d-a18e-825e8c3e709d)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Technical Documentation project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your project has a professional README.md file
✔️Your code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-01 07:14 UTC, ahzamir commented on README.md
> +- LinkedIn: [Hamasa Noorzai](https://www.linkedin.com/in/hamasa-noorzai)
- @Hamas2000 

- Well done Hamasa by implementing the feedback and adding the README.md file to your project:
  - This Link is broken check and solve it.

2024-06-01 11:19 UTC, Hamas2000 commented
@ahzamir  Thank you for your valuable comments. It helped my to do tasks better each time. I will merge it.

2024-06-01 11:20 UTC, merged